spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/delayed-service
          filters:
            - StripPrefix=1
            - name: DelayResponse
              args:
                delay: 3000 # Delay in milliseconds

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/delayed-service
          filters:
            - StripPrefix=1
            - name: DelayResponse
              args:
                delay: 3000 # Delay in milliseconds
server:
  port: 8004