spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/test
          predicates:
            - Path=/users/delayed-service
          filters:
            - StripPrefix=1


        - id: order-service
          uri: http://localhost:8082/test
          predicates:
            - Path=/orders/delayed-service
          filters:
            - StripPrefix=1

server:
  port: 8004